### ISSUE TITLE
FI strategy tag

### ISSUE THREAD

**Issue by wdrav** [SynBioDex/Excel-utilities#7]
In the code, some parts contain the strategy tag, with all of them having the strategy of "enumerate", however, others don't contain the tag. What differentiates parts that have it and parts that do not?

**Comment by jakebeal** [comment]
Can you give an example of a `CombinatorialDerivation` that does not have a `strategy` tag? I think that they are all supposed to have `strategy = enumerate`, so if some don't that sounds likely to be a bug to me.

**Comment by wdrav** [comment]
Thanks for the response, will get to fixing the bug.
